name: replay_trajectory_classification
channels:
- defaults
- conda-forge
- edeno
- anaconda
dependencies:
- "python >= 3.4"
- numpy
- scipy
- pandas
- numba
- statsmodels
- scikit-learn
- joblib
- networkx
- xarray
- dask
- regularized_glm
- patsy
- jupyter
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
