name: replay_trajectory_classification
channels:
- defaults
- conda-forge
- edeno
- anaconda
dependencies:
- "python >= 3.6"
- "numpy >= 1.15"
- "pandas >= 0.22.0"
- numba
- scipy
- statsmodels
- scikit-learn
- matplotlib
- seaborn
- tqdm
- xarray
- dask
- regularized_glm
- loren_frank_data_processing
- ripple_detection
- patsy
- jupyter
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
- pip:
    - upsetplot
